name: simple
channels:
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - decorator=5.1.1
  - executing=0.8.3
  - freetype=2.12.1
  - giflib=5.2.1
  - greenlet=1.1.1
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jpeg=9e
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numpy-base=1.22.4
  - olefile=0.46
  - openssl=1.1.1s
  - packaging=21.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - pluggy=1.0.0
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - pygments=2.11.2
  - pyparsing=3.0.9
  - pytest=7.1.2
  - python=3.8.15
  - python-dateutil=2.8.2
  - pytz=2022.1
  - readline=8.2
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - stack_data=0.2.0
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.1.1
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - asdf==2.10.1
    - asdf-astropy==0.2.2
    - asdf-coordinates-schemas==0.1.0
    - asdf-standard==1.0.3
    - asdf-transform-schemas==0.3.0
    - asdf-wcs-schemas==0.1.1
    - astrodbkit2==0.4
    - astropy==5.1.1
    - astroquery==0.4.1
    - attrs==20.3.0
    - beautifulsoup4==4.9.3
    - bokeh==3.0.2
    - cffi==1.14.5
    - chardet==4.0.0
    - click==7.1.2
    - contourpy==1.0.6
    - cryptography==3.4.7
    - flask==1.1.2
    - flask-cors==3.0.10
    - flask-wtf==0.14.3
    - gwcs==0.18.2
    - html5lib==1.1
    - idna==2.10
    - importlib-metadata==5.1.0
    - importlib-resources==5.10.0
    - itsdangerous==1.1.0
    - jeepney==0.6.0
    - jinja2==2.11.3
    - jmespath==1.0.1
    - jsonschema==3.2.0
    - keyring==23.0.1
    - markdown2==2.4.0
    - markupsafe==1.1.1
    - ndcube==2.0.3
    - numpy==1.22.4
    - pandas==1.5.2
    - pillow==9.3.0
    - pycparser==2.20
    - pyerfa==2.0.0.1
    - pyrsistent==0.17.3
    - pyyaml==5.4.1
    - requests==2.25.1
    - scipy==1.6.2
    - secretstorage==3.3.1
    - semantic-version==2.8.5
    - soupsieve==2.2.1
    - specutils==1.9.1
    - sqlalchemy==1.4.17
    - tqdm==4.61.0
    - typing-extensions==4.4.0
    - urllib3==1.26.4
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - wtforms==2.3.3
    - xyzservices==2022.9.0
    - zipp==3.4.1
